# Generated by Django 6.0.5 on 2026-05-27 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_day', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night'), ('All Day', 'All Day')], default='Morning', max_length=20)),
                ('activity_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.CharField(blank=True, max_length=100)),
                ('transport_info', models.CharField(blank=True, max_length=300)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'itinerary_activities',
                'ordering': ['order', 'time_of_day'],
            },
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('estimated_daily_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'itinerary_day_plans',
                'ordering': ['day_number'],
            },
        ),
    ]
