# Generated by Django 6.0.5 on 2026-05-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerary', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='activity',
            name='day_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itinerary.dayplan'),
        ),
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('trip', 'day_number')},
        ),
    ]
