# Generated by Django 6.0.5 on 2026-05-27 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hotel', 'Hotel/Accommodation'), ('restaurant', 'Restaurant/Dining'), ('attraction', 'Attraction/Sightseeing'), ('transport', 'Transport Hub'), ('shopping', 'Shopping'), ('nature', 'Nature/Park'), ('other', 'Other')], default='other', max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('price_range', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'places',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=200)),
                ('destination_lat', models.FloatField(blank=True, null=True)),
                ('destination_lng', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('INR', 'INR'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('SGD', 'SGD'), ('AED', 'AED')], default='USD', max_length=5)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interests', models.JSONField(default=list)),
                ('travel_style', models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxing', 'Relaxing'), ('Cultural', 'Cultural'), ('Foodie', 'Foodie'), ('Budget', 'Budget'), ('Luxury', 'Luxury'), ('Balanced', 'Balanced')], default='Balanced', max_length=20)),
                ('pace', models.CharField(choices=[('Very Slow', 'Very Slow'), ('Relaxed', 'Relaxed'), ('Moderate', 'Moderate'), ('Energetic', 'Energetic'), ('Packed', 'Packed')], default='Moderate', max_length=20)),
                ('accommodation', models.CharField(choices=[('Hostel', 'Hostel'), ('Budget Hotel', 'Budget Hotel'), ('Hotel', 'Hotel'), ('Boutique Hotel', 'Boutique Hotel'), ('Luxury Resort', 'Luxury Resort'), ('Airbnb/Homestay', 'Airbnb/Homestay')], default='Hotel', max_length=30)),
                ('weather_avg_temp', models.CharField(blank=True, max_length=50)),
                ('weather_condition', models.CharField(blank=True, max_length=200)),
                ('weather_recommendations', models.TextField(blank=True)),
                ('weather_best_months', models.CharField(blank=True, max_length=100)),
                ('budget_breakdown', models.JSONField(default=dict)),
                ('saving_tips', models.TextField(blank=True)),
                ('share_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
