# Generated by Django 6.0.5 on 2026-05-27 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('subscription_type', models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro Explorer'), ('Premium', 'Premium Nomad')], default='Free', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('INR', 'Indian Rupee'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham')], default='USD', max_length=5)),
                ('travel_style', models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxing', 'Relaxing'), ('Cultural', 'Cultural'), ('Foodie', 'Foodie'), ('Budget', 'Budget'), ('Luxury', 'Luxury'), ('Balanced', 'Balanced')], default='Balanced', max_length=20)),
                ('preferred_pace', models.CharField(choices=[('Very Slow', 'Very Slow'), ('Relaxed', 'Relaxed'), ('Moderate', 'Moderate'), ('Energetic', 'Energetic'), ('Packed', 'Packed')], default='Moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
